### ISSUE TITLE
rendering problem in xplayer

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/xapps#1]
Sometimes, xplayer does not draw its window completely after start, i.e. the video runs but the menu bar or the sidebar is not yet visible.
However, giving the focus to another window and back to xplayer appearently forces xplayer to draw completely.

**Comment by surenenfiajyan** [comment]
I have the same problem in Cinnamon. In Mate it seems OK at least for me.

**Comment by JosephMcc** [comment]
This really belongs here: https://github.com/linuxmint/xplayer/issues

I wonder if it's related to this: https://github.com/linuxmint/xplayer/issues/32
