### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by marga-debian** [linuxmint/xapps#13]
Hey there,

I'm looking into uploading this to Debian and I found a bunch of copyright issues.

First and foremost, the only licensing for the project is the COPYING file, that is a GPL-2 file, but the debian/copyright says LGPL. So, which one is it?

Additionally, the AUTHORS file is empty, and there's no Copyright claims anywhere, so it's hard to justify the "Linux Mint" copyright in the debian/copyright file.

On top of this, the xfce4 wallpaper script says "GPL-3", but there's no GPL3 license included in the package. The terms of the GPL state that you need to ship the actual license with the source.

**Comment by clefebvre** [comment]
Fixed following IRC chat.
