### ISSUE TITLE
Settings :: System Info :: Upload System Info Button Does Nothing

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/xapps#14]
@lots0logs commented on [Mon Nov 21 2016](https://github.com/linuxmint/Cinnamon/issues/5997)

1. The system info module assumes that `inxi` is installed and throws an uncaught exception if its not (no feedback is visible to the user though--just seems like the button doesn't do anything). `inxi` isn't a hard dependency in 3.2, is it? 

2. After installing `inxi` and trying again, still nothing happens when pressing the button. Running it from a terminal shows another (different) uncaught exception:
```
 File "/usr/bin/upload-system-info", line 9, in <module>
    output = output.split()[0] # if we have more than one URL, only use the first one
IndexError: list index out of range
```

**Comment by lots0logs** [comment]
@clefebvre @mtwebster

**Comment by leigh123linux** [comment]
The current upload-system-info works fine here on mint or fedora

https://github.com/linuxmint/xapps/blob/master/debian/control#L28

I am -1 for this change as I would like to continue using fpaste as I dislike the idea of using snippets site

**Comment by lots0logs** [comment]
It doesnt work for me on Antergos. I tried to use fpaste's API as documented on its website but it does not work. I cannot figure out why and there is no contact info listed anywhere for who maintains it.

**Comment by leigh123linux** [comment]
Fpaste is mainly fedora

https://pagure.io/fpaste/tree/master
https://github.com/sanjayankur31/fpaste

Mint uses gist instead

**Comment by clefebvre** [comment]
`File "/usr/bin/upload-system-info", line 9, in <module>
    output = output.split()[0] # if we have more than one URL, only use the first one
IndexError: list index out of range`

Why is this happening? is output == None or something?

**Comment by clefebvre** [comment]
^^ this is fixed on master now.

It still doesn't solve the Antergos issue though.

We're happy with gist in Mint and @leigh123linux is happy with fpaste in Fedora. 

@lots0logs if you add the implementation you created in another file, we can call it here, or if you want us to point to something else maybe? We can even test lsb or whatever and do things differently specifically for Antergos, let us know.

**Comment by lots0logs** [comment]
@clefebvre I think we all have tons of more important stuff on our never ending todo lists so we'll go ahead and use gist as well :wink:

**Comment by clefebvre** [comment]
No pb :)
