### ISSUE TITLE
File open/save dialogs look inconsistent and ugly

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/xapps#2]
It's not a bug, however it's very annoying, the file dialogs look out of place and are very ugly, I think the problem is caused by the new GTK libraries.

Here are my screenshots for comparison.

![screenshot at 2016-08-25 00-18-59](https://cloud.githubusercontent.com/assets/13224708/17946932/7b832952-6a5b-11e6-860d-14be390a8a06.png)
1. The new one(used by xapps, Firefox and most others)

![screenshot at 2016-08-25 00-25-57](https://cloud.githubusercontent.com/assets/13224708/17946941/813372d0-6a5b-11e6-964c-b370d30e3a11.png)
2. The old one(still used by LibreOffice)

Both Mate and Cinnamon are affected (didn't tested XFCE and KDE ).

**Comment by JosephMcc** [comment]
Those are the default file open dialogs from gtk3. This complaint really needs to go upstream with gtk3.
