### ISSUE TITLE
USB formatter offers to format wrong USB stick

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/xapps#28]
On two Mint laptops, one Cinnamon and one XFCE, I tried to use the bundled USB formatting tool. On both computers, an icon for the stick (which is made by Lexar) appeared on my desktop and in both cases the stick was identified as being called 'Linux Mint'. On both laptops, though, the formatting program identified the stick as 'Kingston Data Traveller'. Earlier today I had had a Kingston USB in the drives of both computers.

Faced with this, I worried about the format and resorted to formatting the stick on . . Windows.

**Comment by clefebvre** [comment]
Ok, please post this against mintstick though, it's not related to xapps.
