### ISSUE TITLE
Amtk library, a GtkUIManager replacement based on GAction, to create traditional UIs

### ISSUE THREAD

**Issue by swilmet** [linuxmint/xapps#29]
Hi,

I'm a GNOME developer who doesn't really like GtkHeaderBar for one of my application, I wanted to keep a traditional UI with a menubar, toolbar and statusbar. But GtkUIManager/GtkAction are deprecated, and there are several problems with GMenu and how to create a toolbar with what GTK+ 3 provides.

So I just wanted to let you know that I've created a new library, called Amtk, the acronym for “Actions, Menus and Toolbars Kit”. It is based on GAction.

There is a detailed introduction here, describing the problems with what GTK+ provides:
https://developer.gnome.org/tepl/unstable/amtk-intro.html

Amtk is currently a sub-library part of Tepl:
https://wiki.gnome.org/Projects/Tepl

See also:
https://wiki.gnome.org/Projects/GTK+/Menus

Feel free to close the issue, the intention was just to provide you the information ;-) I haven't find a mailing list to contact you on the Linux Mint website.

**Comment by JosephMcc** [comment]
I believe I saw a blog post from you about this awhile back. Does it support a replacement for things like GtkImageMenuItem? The removal of that is one of the annoyances in newer gtk versions. I think most Mint users expect a certain menu style.

**Comment by swilmet** [comment]
Yes, I wrote a blog post on the planet GNOME, so that's great if you were already aware of the project.

For a GtkImageMenuItem replacement, there is the [amtk_menu_item_set_icon_name()](https://developer.gnome.org/tepl/unstable/tepl-3.0-AmtkMenuItem.html#amtk-menu-item-set-icon-name) function. But the problem is that the icon is not in the same column as the check and radio drawings, there is a large margin on the left, as is also the case with GMenu. The problem is listed on this wiki page:
https://wiki.gnome.org/Projects/Tepl/DevNotes/Amtk

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this but thank you for providing the info. I personally follow your blog posts since much of it is gtksourceview related :)
