### ISSUE TITLE
File open dialog: address bar settings does not get obeyed

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/xapps#3]
Tested with xed and xreader in LM 18 Cinnamon 64 bit

Click to open a file, the dialog shows the address bar as breadcrumb.
Now press ctrl-L to switch the address bar into edit mode.

Close the dialog and reopen it: It does again show in breadcrumb mode.

If you look in dconf at org.gtk.Settings.FileChooser you can see, that the value for location-mode gets changed according to the result of pressing ctrl-L. But although the value is set to filename-entry the dialog gets opened with the breadcrumb.

Bug or intended? I consider it as bug, as the current setting should get obeyed (just as e.g. Nemo does).

**Comment by surenenfiajyan** [comment]
I also hate these "shiny new" file dialogs, [they look inconsistent and ugly](https://github.com/linuxmint/xapps/issues/2). Some GNOME 3 madness.

**Comment by JosephMcc** [comment]
That dialog is a gtk dialog. The bug/feature request should really be filed upstream with gtk.
