### ISSUE TITLE
Ability to hide menubar

### ISSUE THREAD

**Issue by astier** [linuxmint/xapps#43]
### Feature Request
Ability to hide the menubar as a standard feature for all xapps with a menubar.

### Problem
A lot of the xapps (e.g. xplayer, xed, xreader, etc.) do not support hiding the menubar. I personally (and I believe many other people) don't use the menubar most of the time. This leads to the following issues:
- Valuable screen-space is wasted. This is especially a problem for people with small screens.
- Unmodern and cluttered look.

**Comment by memeplex** [comment]
I entered here to request exactly the same.

>  the gnome-apps because they solve this issue very elegantly

I don't fully agree with this statement. They look elegant, right. But their "solution" is to revolutionize the entire desktop in the most invasive way. Imagine if they had taken a more evolutionary approach: a standard way to hide existent menu bars (maybe coupled with a ctrl-p style interface to quickly access menu entries), integrating the title bar with the top bar for maximized windows... That would make apps more elegant and sleek and would have saved vertical space, all at a very low cost for both downstream developers and end users. Instead we have now a solution that provides a handful of fancy apps with strange symbolic icons at the top, plus uncertainty and inconsistency for the rest, and this several years too late. And even if every app developer were eager to add a header bar to his/her app (which I seriously doubt) it's not even a general solution: what fancy icons will you put at the top of vim or emacs? I just want my tittle bar hidden there, but that's outside the scope of the wm now. Not to talk about consistency: do you think standard window buttons and focus indicators will work consistently across desktops, apps and toolkits?

**Comment by astier** [comment]
linuxmint/xed#213

**Comment by semioticrobotic** [comment]
Came here to request this feature. Glad to see I'm not alone. Sad to see no plans for addressing it.

**Comment by clefebvre** [comment]
Hi,

I wouldn't oppose this but it's not something that would be done at lib level. These menubars aren't Xapp menubars, they're GTK menubars in individual apps (xed, xreader etc..).

If someone contributes pull requests to implement this in these apps, we'll consider them. The menubars would obviously need to be visible by default, but we could have a menu item and keyboard shortcut to toggle that.
