### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by killerkalamari** [linuxmint/xapps#50]
I couldn't find any build instructions, so here's what I came up with for Ubuntu 18.04, hope it helps!

1. Install these packages (and probably others, as I already had a lot of gtk-related dev packages on my system): 
build-essential, meson, valac, libgnomekbd-dev, python-gi-dev 
2. Run these commands: 
```
cd xapps
mkdir builddir
meson builddir
cd builddir
ninja
sudo ninja install
```

**Comment by collinss** [comment]
On debian based systems (i.e. Ubuntu, Mint, etc) it's actually recommended to use
```
dpkg-buildpackage
cd ..
sudo dpkg -i *.deb
```
Otherwise you run into issues such as not being managed by apt.

**Comment by clefebvre** [comment]
sudo mk-build-deps -ir
dpkg-buildpackage
sudo dpkg -i ../*.deb

**Comment by clefebvre** [comment]
It's not specific to this project, all our projects build like this. We're working on a developer guide, but it's not ready yet.
