### ISSUE TITLE
Static analysis report

### ISSUE THREAD

**Issue by shlyakpavel** [linuxmint/xapps#66]
Hello. I hope this might be helpful.
https://github.com/linuxmint/xapps/blob/ed1f981014c7d66713c094ed9dd230803db417ba/libxapp/xapp-icon-chooser-dialog.c#L845-L852
https://github.com/linuxmint/xapps/blob/ed1f981014c7d66713c094ed9dd230803db417ba/libxapp/xapp-gtk-window.c#L490-L491
Have a nice day!

**Comment by mtwebster** [comment]
Thanks!
