### ISSUE TITLE
Shortcut to hide toolbar

### ISSUE THREAD

**Issue by robsdedude** [linuxmint/xapps#73]
I came here because I was looking for keyboard shortcut to hide the toolbar in Xreader. This is currently only possible by using a menu entry. I'm not sure if keyboard shortcuts are handled at lib level (couldn't find something in the code), but the issue over a Xreader suggests so: https://github.com/linuxmint/xreader/issues/216

It might also be worth thinking about a way to customize keyboard shortcuts (in case this isn't something the lib already supports).

**Comment by mtwebster** [comment]
This is in fact an xreader thing.  Reopened original bug.
